### ISSUE TITLE
PascalCase only for .jsx files??

### ISSUE THREAD

**Issue by KingScooty** [sindresorhus/eslint-plugin-unicorn#23]
Is there a way to enforce PascalCase, but only for .jsx files?

**Comment by jfmengels** [comment]
Not with our `filename-case` rule at this moment.
What is it that you would really want? Would you want to enforce PascalCase only for some files, and then some other case for the rest?

**Comment by KingScooty** [comment]
Yeah, so kebab case for all files that aren't .jsx files. 
Since jsx components are always defined with pascal case, i'd like to name the files accordingly too.

**Comment by jamestalmage** [comment]
That seems really goofy. You could then conceivably have `some-item.js` and `SomeItem.jsx` in the same directory. That seems.like a bad plan. It also messes with alphabetical ordering

**Comment by KingScooty** [comment]
Yeah, i guess. I don't make a habit of mixing the two filetypes together though. It just feels weird not using  a pascal case for jsx files, when they're always referred to in pascal case in the code. Maybe it's just me!

**Comment by jamestalmage** [comment]
I always use kebab case for files, regardless. I find directory listings much easier to read that way.

**Comment by tonytonyjan** [comment]
It's common to see mixed file naming in react projects.

**Comment by corbinu** [comment]
I would also like a per file extension option. Vue.js by default has capitol names for components and lowercase fro JS files.

**Comment by milesj** [comment]
+1 to this.

In most projects, the name of the file matches the type of content in the file. If it's a class, pascal case, if it's a function, camel case, if it's a bin/exe, kebab case. Assuming that all files follow the same pattern is inherently wrong.

**Comment by corbinu** [comment]
Would you all be open to this if I wrote a PR?

**Comment by zeorin** [comment]
What about using ESLint's built-in overrides system:
```yaml
  overrides:
    - files:
        - '**/*.jsx'
      rules:
        unicorn/filename-case:
          - warn
          - case: pascalCase
    - files:
        - '**/index.jsx'
      rules:
        unicorn/filename-case: off
```
