### ISSUE TITLE
Is there a way to turn all rules level to warn/error?

### ISSUE THREAD

**Issue by amankkg** [sindresorhus/eslint-plugin-unicorn#289]
E.g. as [`react-hooks` plugin](https://github.com/facebook/react/blob/dab2fdbbbd6eb560523fe2146c153f6a24e2f8dc/packages/eslint-plugin-react-hooks/src/index.js#L14) allows to do
```YAML
# rest of ESLint config
rules:
  prettier/prettier: 'error'
  react-hooks/rules-of-hooks: 'error'
  unicorn/rules-of-unicorn?: 'error'
# rest of ESLint config
```
