### ISSUE TITLE
consistent-function-scoping: false positive with name collision

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/eslint-plugin-unicorn#854]
test.js:
```js
const a = () => {
  const fn = () => "a";
  return fn();
};

const b = () => {
  const fn = () => "b";
  return fn();
};
````
.eslintrc.yaml:
````yaml
plugins:
  - unicorn

rules:
  unicorn/consistent-function-scoping: [2]
````
Output:
````
  2:17  error  Move arrow function 'fn' to the outer scope  unicorn/consistent-function-scoping
  7:17  error  Move arrow function 'fn' to the outer scope  unicorn/consistent-function-scoping
````

It's not possible to move the two `fn` to the outer scope because their names would collide.
